### ISSUE TITLE
Restricted RSS feeds

### ISSUE THREAD

**Issue by nibrahim** [pythonindia/in.pycon.org#12]
An RSS feed of the entire wiki changing is confusing and pointless. 

IT would be nice if we could have a single page ("news" or something - maybe the blog referred to in the other post). Changes on that would be added to the official feed but only the new content and not an old vs. new diff. This would work fine.

**Comment by anandology** [comment]
The RSS feed of blog sovles this issue.

http://in.pycon.org/2010/blog/feed.rss
