### ISSUE TITLE
Pycon site lacks favicon

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#13]
There is no favicon on http://in.pycon.org/2010 site. We should set the favicon to the Python.org python icon.

Get it from,
http://www.getfavicon.org/results.php?url=python.org

**Comment by ideamonk** [comment]
making one from previous year's logo, or shall we put a python logo?

**Comment by pythonhacker** [comment]
We can put Python logo - that seems to be the custom in Pycons.

**Comment by ideamonk** [comment]
Nice, added in commit - http://github.com/anandology/in.pycon.org/commit/cef689cd74fa98352d1da7331db37d7658ece4b8

**Comment by ideamonk** [comment]
Favicon would be reflected on website as soon as its updated.
