### ISSUE TITLE
Sponsor icon size and wording

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#14]
The sponsor icon sizes are not uniform. For example, the PSF icon "sticks out" since it is wider than the MSRIT icon. We need all icons to be of uniform size so that they display nicely as a column.
Also need to change the wording to "GOLD", "SILVER", "VENUE" etc instead of the current "Gold sponsor", 'Venue sponsor" which is redundant.

The Pycon AUS site can be used as a template for this.

http://pycon-au.org/2010/conference/proposals/

**Comment by ideamonk** [comment]
changed to short words, something similar to pycon aus now.

**Comment by anandology** [comment]
This is fixed now.
