### ISSUE TITLE
Move the "2009" menu item to right most side of menu bar

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#15]
The "2009" menu item which links to last years conference site doesn't belong with the other items. We need to move it to the right of the menu bar with a reduced font size and a slightly less bright white, so that it gives the correct visual cue to the site visitor.

**Comment by ideamonk** [comment]
Shifted to right as in http://twitpic.com/20oz1t/full

**Comment by pythonhacker** [comment]
Looks good to me. Please push the changes to site.

**Comment by anandology** [comment]
This is live now.
