### ISSUE TITLE
The horizontal rule looks "stitched" (visual issue)

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#17]
The horizontal rule (hr) element on the pycon website has a "stitched" look which is not very nice. Instead have a thinner line with minute breaks which are barely registered by the visitor. The stitched look is not appealing.

Same issue is seen in the top menu bar where it has two horizontal rules running on top and bottom.

**Comment by ideamonk** [comment]
The menu has caused issues in the back too, looking odd on FF 3.0 earlier, after a fix looks odd on IE7, I'm experimenting with a little layout change in a separate branch so as to simplify it and have an expanding layout if possible. Let me see how it goes, if okay we can merge back to master.

**Comment by nibrahim** [comment]
The stitched look looks nice for the menubar header. For the content, it looks less than perfect.

**Comment by ideamonk** [comment]
Ah made it into a thin line.

**Comment by pythonhacker** [comment]
Closing.
