### ISSUE TITLE
All admin controls plus status should be in the bottom

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#20]
Right now only "Admin login" has been moved to the bottom. We need the "Logout" as well as the "Welcome <Admin>" message to be moved to the bottom as well. It doesn't belong to the menu bar where it is right now.

**Comment by ideamonk** [comment]
Would look like this in next update http://twitpic.com/20ntbc/full

**Comment by pythonhacker** [comment]
Cool. I will close this.

**Comment by pythonhacker** [comment]
Closing the issue since changes are done.
