### ISSUE TITLE
Page real estate is limited artificially

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#21]
If you look at the site you can see that nearly 2 cm is lost on either side of the page with the writeable area being reduced to the rest of it. This cramps the page content in my opinion. Why leave so much valuable real estate unused ? Please reduce the border sizes.

**Comment by ideamonk** [comment]
Converting to expanding layout with greater width.

**Comment by ideamonk** [comment]
The layout ears less margin on sides now - 99% width, yet maintains minimum width of 900px in case people resize it/ open on smaller display. Content - 70%, sponsor sidebar - 30%.

**Comment by pythonhacker** [comment]
Are the changes live on the site ?

**Comment by ideamonk** [comment]
Yes I think this one is live now.

**Comment by pythonhacker** [comment]
Cool. We need to align the sponsor icons to the right border and the top-level image box also (as indicated in issue #14) for the look to be perfect. Btw what is that new "{ ... }" around the image box. It doesn't look very nice.

**Comment by pythonhacker** [comment]
Closing the issue.
