### ISSUE TITLE
Tweet talk title should be enclosed in quotes

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#24]
Please enclose talk title in quotes. 
For example, it should be,

[New talk submitted - "Plugin frameworks : 3 approaches to designing plugin APIs" by Noufal Ibrahim] instead of [New talk submitted - Plugin frameworks : 3 approaches to designing plugin APIs by Noufal Ibrahim].

See my similar comment for issue #9.

**Comment by anandology** [comment]
Reopened #9. Closing this.
