### ISSUE TITLE
"Talks" page doesn't show all talks !

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#25]
The talks page currently shows,

```
* Building Scalable Apps using Google App Engine - Pranav Prakash
* Python and golf - Kenneth Gonsalves
* GUI Programming using PyQt - Ankur Gupta
* Case study: Opendevice & Python - Srirangan
```

What happend to my PDF talk and the talk submitted by Noufal ?
If this is a temporary issue, it is fine, but if it is a bug, it has to be fixed.

**Comment by nibrahim** [comment]
This is a serious problem.

**Comment by pythonhacker** [comment]
Can we sort this out quickly ? We are gaining tempo slowly and ppl are noticing this.
I had Shashwat Anand chat with me regarding this page now for example.

**Comment by pythonhacker** [comment]
Please remove "Test Talk" from the interface.

**Comment by pythonhacker** [comment]
Can we number the talks instead of showing them in bullets ?

**Comment by pythonhacker** [comment]
Closing this
