### ISSUE TITLE
The "Talks" page should be a global menu item and should show talk status

### ISSUE THREAD

**Issue by pythonhacker** [pythonindia/in.pycon.org#26]
Currently the "Talks" page is almost hidden, found only in the CFP page.
We need to add this to the global menu bar and when one clicks, it
should show a table like this,

---
## Talk Title          |  Submitted By            |          Status           

How I killed     |  Snake Charmer        | Under review (Orange color)
## the Python       |

How I fought   | Snake Catcher          |          Approved (Green color with
the Python      |                                      |          a tick mark after it if possible) 

Let us not show unapproved talks. Unapproved talks (rejected) will still
be shown "Under review". We will inform the authors directly about this.

Comments anyone ?

**Comment by pythonhacker** [comment]
Goodness! The table didn't display well as I thought. Here is it.

<table>
    <tr>
        <td>Talk Title</td>
      <td>Submitted By</td>
       <td>Status</td>
    </tr>
   <tr>
        <td>How I fought the Python</td>
      <td>Snake Charmer</td>
       <td>Under review (Orange color)</td>
    </tr>
   <tr>
        <td>How I caught the Python</td>
      <td>Snake Catcher</td>
       <td>Approved (Green color)</td>
    </tr>
</table>

**Comment by nibrahim** [comment]
I think the "talk" link should be prominent (maybe even the landing page for the website as a whole since it'll be dynamic - good SEO) but I don't think the colours and stuff are necessary. We'll just put a "Submitted talks - these will be reviewed and shortlisted"  header during the CFP process and when we're done, publish a proper list.

**Comment by pythonhacker** [comment]
Another enhancement could be to have a "Most recent submitted talk" widget on the Home page that lists the 2 most recent submitted talks ?

**Comment by nibrahim** [comment]
Can we get this done quickly? We need to spam a lot of people and if the talks are not quickly accessible/visible, it's bad for publicity.

**Comment by pythonhacker** [comment]
Please guys, don't delay this. I would like to send the request to all delegates before July 1st, i.e at most by tomorrow the 30th. 
For the time being, nothing fancy except a numbered list of talks as against a bulleted list and a global "Talk" Menu. The private URL to edit the talks can come later. Hope this will be done by tomorrow evening.

**Comment by anandology** [comment]
Added talks to menu and improved talks page. closed by c8a591293f4f58678fccb53bc71aba1bd8cc5650
