### ISSUE TITLE
Main body width to be 60% or so

### ISSUE THREAD

**Issue by nibrahim** [pythonindia/in.pycon.org#27]
The current full width body doesn't look as good as the previous one which had some more margins. 

Also, the picture slideshow has _braces_ on both sides. Dude! This is a Python conference. What were you thinking? :P

**Comment by ideamonk** [comment]
Lol but ah the expanding layout made the slides look bad, anyways I'll remove them, but do braces signify something really opposite?
Actually I had no intention for them to represent something ! 

Guys shall we go back to a fixed width layout? or shall we go for more margins+expanding?

Awaiting comments, braces getting removed for sure.

**Comment by ideamonk** [comment]
Alright guys, seems like this change though suggested to be brought in, got more opposing opinion, we have a favour of 1:2 while I stay neutral, so I shall revert back.

Ref: issue 21 - http://github.com/anandology/in.pycon.org/issues/closed#issue/21

**Comment by ideamonk** [comment]
Done, back to original, leveled bottom borders of sponsor, and content to make them look leveled/neat

**Comment by nibrahim** [comment]
Is this change pushed to the live server? It's still 100% for me.

**Comment by anandology** [comment]
This is fixed now.
