### ISSUE TITLE
Publicity page needed on site

### ISSUE THREAD

**Issue by nibrahim** [pythonindia/in.pycon.org#28]
We need a page for "publicity". 

It should have the badges of "Set 6" from http://wiki.python.org/moin/PyConIndia2010/Badges and there should be HTML snippets which people can cut/paste onto their sites/blogs. Something like

```
 <a href="http://in.pycon.org"><img src="http://in.pycon.org/images/support.png" alt="I support PyCon India 2010"></a>
```

**Comment by nibrahim** [comment]
I've created a page at http://in.pycon.org/2010/publicity but it needs to be linked from the top navbar.

**Comment by anandology** [comment]
Done.
