### ISSUE TITLE
Broken header on the site with some browsers

### ISSUE THREAD

**Issue by nibrahim** [pythonindia/in.pycon.org#29]
I see a broken right edge with the banner with FF 3.0.19. With a newer FF on a smaller screen, it looks fine. The broken edge looks like this http://twitpic.com/20ydge and http://twitpic.com/20ydb8
(I've circled the problem part).

**Comment by anandology** [comment]
Looks like that is an issue with the wide-layout. We are now back to the old layout.

**Comment by nibrahim** [comment]
It was there with the narrow layout as well but not on all browsers - http://twitpic.com/20ydb8
