### ISSUE TITLE
CFP - missing validation

### ISSUE THREAD

**Issue by ideamonk** [pythonindia/in.pycon.org#4]
1. No validation to CFP - This is a big problem. We need
   to add validation to CFP fields and refuse from submitting
   if the author fails to enter valid date in the key fields.
   These are Title, Authors, Email, Profile, Summary and
   Outline.  We need to be intelligent in the evaluation and
   not just look for empty string.

**Comment by ideamonk** [comment]
Options - 
1. frontend js based checks,
2. captcha for avoiding auto submissions

Maybe a combination of both.

**Comment by ideamonk** [comment]
ReCAPTCHA implemented, 
Tried web.py's validator in Form class, 

```
Validator("Summary should be at least 10 words or more",
                                    lambda i: len(i.summary.split())>=10)
```

But seems like the frontend doesn't take it, this message comes as something other than $form.notes.note which I wonder as to what is.

**Comment by ideamonk** [comment]
Added summary validator, now we can have any kind of validators defined in code.py :)

**Comment by ideamonk** [comment]
Hey guys is this issue closable now?

Right now we've wordcount validations sans captcha

**Comment by pythonhacker** [comment]
The only thing missing by me is that we are not showing "Please fix the errors shown in red" if there are errors. The form just returns and we show the errors per field, not a top-level message.

**Comment by ideamonk** [comment]
Added a message on submission page http://twitpic.com/20nvio/full

**Comment by pythonhacker** [comment]
Great :)

**Comment by pythonhacker** [comment]
If this is done, we can close the issue.

**Comment by ideamonk** [comment]
This is active on main site, just checked out

**Comment by anandology** [comment]
Thanks ideamonk!

**Comment by ideamonk** [comment]
Hey guys, thanks for setting up and all the help :)
I couldn't fix more from 30th, and would be back to bangalore on 8th, right now in Delhi, so.
